{
  "hash": "3d5513a8070c8e1b6ab7203f0763b70d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Weekly Expenditure\"\nauthor: \"Ashmita Biswas\"\n---\n\n# Weekly expenditure\n\nAre Srishti students really Money-pal? 💸\n\n![](images/clipboard-1362529375.png)\n\n## About the Data\n\nThis data set is derived from the peasants of Srishti Manipal Institute to analyse the spending behaviour in a week.\n\n## Data Dictionary\n\n**Qualitative variables**\n\n:   **Name:** Name of the student (aka. peasant)\n\n:   **Gender:** Gender of the students categorized as 'Male' & 'Female'\n\n**Quantitative variables**\n\n:   **Total_Expenditure_Last_Week:** Total amount of money spent in the last week by the student\n\n## Hypothesis\n\n-   Do Srishti students spend more than what is normally expected?\n\n**Something more to look for**\n\n-   Is there a difference in spending behaviour amongst different gender?\n\n### Setup\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ purrr     1.1.0\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\nLoading required package: scales\n\n\nAttaching package: 'scales'\n\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n\n\nLoading required package: ggridges\n\n\nNew to ggformula?  Try the tutorials: \n\tlearnr::run_tutorial(\"introduction\", package = \"ggformula\")\n\tlearnr::run_tutorial(\"refining\", package = \"ggformula\")\n\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\n\nAttaching package: 'mosaic'\n\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\n\nThe following object is masked from 'package:scales':\n\n    rescale\n\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n\n\n\nAttaching package: 'skimr'\n\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n\n\n\nAttaching package: 'naniar'\n\n\nThe following object is masked from 'package:skimr':\n\n    n_complete\n\n\n\nAttaching package: 'janitor'\n\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n\n\n\nAttaching package: 'tinytable'\n\n\nThe following object is masked from 'package:ggplot2':\n\n    theme_void\n\n\n\nAttaching package: 'crosstable'\n\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n:::\n\n\n### Inspecting the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_data <- read_csv(\"~/Documents/R_work/DataRchive/posts/A3_Ashmita/Datasets/4-weekly_expenditure.csv\") %>%\njanitor::clean_names(case = \"snake\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\nRows: 40 Columns: 6\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" chr\n(2): Name, Gender dbl (1): Total_Expenditure_Last_Week lgl (3): ...4, ...5,\n...6\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...4`\n• `` -> `...5`\n• `` -> `...6`\n```\n\n\n:::\n\n```{.r .cell-code}\nweekly_expends_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 40 × 6\n   name      gender total_expenditure_last_week x4    x5    x6   \n   <chr>     <chr>                        <dbl> <lgl> <lgl> <lgl>\n 1 Radha     Female                        2000 NA    NA    NA   \n 2 Prerana   Female                        1200 NA    NA    NA   \n 3 Chris     Male                         15000 NA    NA    NA   \n 4 Nireeksha Female                        3620 NA    NA    NA   \n 5 Supraj    Male                           560 NA    NA    NA   \n 6 Adit      Male                          2200 NA    NA    NA   \n 7 Shweta    Female                        1500 NA    NA    NA   \n 8 Diya      Female                        1206 NA    NA    NA   \n 9 Kshama    Female                        1400 NA    NA    NA   \n10 Savannah  Female                        2500 NA    NA    NA   \n# ℹ 30 more rows\n```\n\n\n:::\n:::\n\n\n### Checking for missing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_data %>%\n  visdat::vis_miss()\n```\n\n::: {.cell-output-display}\n![](Weekly_expends_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_data %>%\n  visdat::vis_dat()\n```\n\n::: {.cell-output-display}\n![](Weekly_expends_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n*Removing the unfilled columns*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_mod1 <- weekly_expends_data%>% \nselect(name, gender, total_expenditure_last_week)\n\nweekly_expends_mod1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 40 × 3\n   name      gender total_expenditure_last_week\n   <chr>     <chr>                        <dbl>\n 1 Radha     Female                        2000\n 2 Prerana   Female                        1200\n 3 Chris     Male                         15000\n 4 Nireeksha Female                        3620\n 5 Supraj    Male                           560\n 6 Adit      Male                          2200\n 7 Shweta    Female                        1500\n 8 Diya      Female                        1206\n 9 Kshama    Female                        1400\n10 Savannah  Female                        2500\n# ℹ 30 more rows\n```\n\n\n:::\n:::\n\n\n### Munging the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_mod2 <- weekly_expends_mod1 %>% \n  mutate(gender = as.factor(gender))\n\nweekly_expends_mod2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 40 × 3\n   name      gender total_expenditure_last_week\n   <chr>     <fct>                        <dbl>\n 1 Radha     Female                        2000\n 2 Prerana   Female                        1200\n 3 Chris     Male                         15000\n 4 Nireeksha Female                        3620\n 5 Supraj    Male                           560\n 6 Adit      Male                          2200\n 7 Shweta    Female                        1500\n 8 Diya      Female                        1206\n 9 Kshama    Female                        1400\n10 Savannah  Female                        2500\n# ℹ 30 more rows\n```\n\n\n:::\n:::\n\n\n## Examining the Data\n\nSummarizing in a table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(weekly_expends_mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     name              gender   total_expenditure_last_week\n Length:40          Female:20   Min.   :  365              \n Class :character   Male  :20   1st Qu.: 1204              \n Mode  :character               Median : 2350              \n                                Mean   : 4833              \n                                3rd Qu.: 4475              \n                                Max.   :50000              \n```\n\n\n:::\n:::\n\n\n#### Observation\n\n-   We can see that there is an equal (50%) representation of male and female, thus eliminating any gender bias in the data collection.\n\n-   The average spending of these peasants in a week is Rs. 2350\n\n-   Spending varies dramatically from lowest record being Rs. 365 to highest being Rs. 50,000 per week\n\n-   25% os these students spend under ₹1,204 weekly and top 25% spend over ₹4,475.\n\n### What is the spending behaviour\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_mod2 %>%\n  gf_boxplot(~total_expenditure_last_week, orientation = \"y\") %>%\n  gf_labs(\n    title = \"Weekly Spending Distribution\",\n    x = \"Total Expenditure (in Rs.)\", \n    y = \"Students\"\n  )\n```\n\n::: {.cell-output-display}\n![](Weekly_expends_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_mod2 %>%\n  arrange(total_expenditure_last_week) %>%\n  mutate(name = fct_inorder(name)) %>%\n  gf_col(total_expenditure_last_week ~ name, fill = ~gender) %>%\n  gf_labs(\n    title = \"=Weekly Spending=\",\n    x = \"Student\",\n    y = \"Total Expenditure (in Rs.)\"\n  ) %>%\n  gf_theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](Weekly_expends_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n### How do different gender spend differently?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_mod2 %>%\n  gf_boxplot(log10(total_expenditure_last_week) ~ gender, fill = ~gender, orientation = \"x\") %>%\n  gf_labs(\n    title = \"Weekly Spending Distribution by Gender\",\n    x = \"Gender\", \n    y = \"Total Expenditure (in Rs.)\",\n    subtitle = \"Comparing median spending and variability\"\n  )\n```\n\n::: {.cell-output-display}\n![](Weekly_expends_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_mod2 %>%\n  gf_dens(~total_expenditure_last_week, colour = ~gender, fill = ~gender, size = 1, alpha = 0.5) %>%\n  gf_labs(\n    title = \"Spending Density by Gender\",\n    x = \"Total Expenditure\",\n    y = \"Density\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Weekly_expends_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_mod2 %>%\n  group_by(gender) %>%\n  summarise(mean_spending = mean(total_expenditure_last_week)) %>%\n  gf_col(mean_spending ~ gender, fill = ~gender) %>%\n  gf_labs(\n    title = \"Average Weekly Spending by Gender\",\n    x = \"Gender\",\n    y = \"Mean Expenditure (in Rs.)\"\n  )\n```\n\n::: {.cell-output-display}\n![](Weekly_expends_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekly_expends_mod2 <- function(x) {\n  sign(x) * total_expenditure_last_week(abs(x))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt2 <- wilcox.test(weekly_expends_mod1$total_expenditure_last_week,\n                  mu = 2000,\n                  alternative = \"two.sided\",\n                  conf.int = TRUE,\n                  conf.level = 0.95) %>%\n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(weekly_expends_mod1$total_expenditure_last_week,\n: cannot compute exact p-value with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(weekly_expends_mod1$total_expenditure_last_week,\n: cannot compute exact confidence interval with ties\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(weekly_expends_mod1$total_expenditure_last_week,\n: cannot compute exact p-value with zeroes\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in wilcox.test.default(weekly_expends_mod1$total_expenditure_last_week,\n: cannot compute exact confidence interval with zeroes\n```\n\n\n:::\n\n```{.r .cell-code}\nt2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  estimate statistic p.value conf.low conf.high method               alternative\n     <dbl>     <dbl>   <dbl>    <dbl>     <dbl> <chr>                <chr>      \n1    2875.       534  0.0452    2013.     4250. Wilcoxon signed ran… two.sided  \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Weekly_expends_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}