{
  "hash": "905c068aa5ad0f55beef29386eb9370b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Believe in God\"\nauthor: \"Ashmita Biswas\"\n---\n\n# Believe in God\n\nReal or Myth?\n\n![](images/clipboard-1676803513.png)\n\n## About the Data\n\nThis data set explores the spiritual landscape of art students. A quantitative analysis of divine belief patterns at Srishti Manipal Institute.\n\n## Data Dictionary\n\n**Qualitative Variables**\n\n:   **Name:** Name of the student\n\n:   **Gender:** Gender of the student, categorized by 'Male' and 'Female'\n\n:   **Believe_in_God:** Students' believe in God, categorized as 'Yes' and 'No'\n\n## Hypothesis\n\n-   In an art & design educational environment, will students show higher rates of non-belief compared to the general population due to exposure to diverse perspectives and critical thinking emphasis?\n\n**Something more to look for**\n\n-   There might be gender differences in religious belief patterns due potential cultural socialization influences.\n\n### Setup\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ purrr     1.1.0\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\nLoading required package: scales\n\n\nAttaching package: 'scales'\n\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n\n\nLoading required package: ggridges\n\n\nNew to ggformula?  Try the tutorials: \n\tlearnr::run_tutorial(\"introduction\", package = \"ggformula\")\n\tlearnr::run_tutorial(\"refining\", package = \"ggformula\")\n\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\n\nAttaching package: 'mosaic'\n\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\n\nThe following object is masked from 'package:scales':\n\n    rescale\n\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n\n\n\nAttaching package: 'skimr'\n\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n\n\n\nAttaching package: 'naniar'\n\n\nThe following object is masked from 'package:skimr':\n\n    n_complete\n\n\n\nAttaching package: 'janitor'\n\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n\n\n\nAttaching package: 'tinytable'\n\n\nThe following object is masked from 'package:ggplot2':\n\n    theme_void\n\n\n\nAttaching package: 'crosstable'\n\n\nThe following object is masked from 'package:purrr':\n\n    compact\n\n\nLoading required package: grid\n\n\nAttaching package: 'vcd'\n\n\nThe following object is masked from 'package:mosaic':\n\n    mplot\n\n\nLoading required package: gnm\n\n\nAttaching package: 'gnm'\n\n\nThe following object is masked from 'package:lattice':\n\n    barley\n\n\n\nAttaching package: 'vcdExtra'\n\n\nThe following object is masked from 'package:dplyr':\n\n    summarise\n```\n\n\n:::\n:::\n\n\n### Inspecting the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_data <- read_csv(\"~/Documents/R_work/DataRchive/posts/A3_Ashmita/Datasets/5-believe_in_god.csv\") %>%\njanitor::clean_names(case = \"snake\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 47 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): Name, Gender, Believe_in_God\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nbelieve_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 47 × 3\n   name      gender believe_in_god\n   <chr>     <chr>  <chr>         \n 1 Sanjana   Female Yes           \n 2 Tathasthu Male   Yes           \n 3 Vaibhav   Male   Yes           \n 4 Siddharth Male   Yes           \n 5 Ashik     Male   No            \n 6 Kshirab   Female Yes           \n 7 Niyosha   Female Yes           \n 8 Charvi    Female No            \n 9 Anoti     Female Yes           \n10 Dhruv     Male   No            \n# ℹ 37 more rows\n```\n\n\n:::\n:::\n\n\n### Checking for missing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_data %>%\n  visdat::vis_miss()\n```\n\n::: {.cell-output-display}\n![](Beleive_in_God_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_data %>%\n  visdat::vis_dat()\n```\n\n::: {.cell-output-display}\n![](Beleive_in_God_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThere are missing values in the data as some students might have chose to not answer the question. Hence **removing unanswered entries**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_mod1 <- believe_data %>% \n  naniar::replace_with_na_all(condition = ~ .x %in% common_na_strings) %>% \ndrop_na()\nbelieve_mod1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 41 × 3\n   name      gender believe_in_god\n   <chr>     <chr>  <chr>         \n 1 Sanjana   Female Yes           \n 2 Tathasthu Male   Yes           \n 3 Vaibhav   Male   Yes           \n 4 Siddharth Male   Yes           \n 5 Ashik     Male   No            \n 6 Kshirab   Female Yes           \n 7 Niyosha   Female Yes           \n 8 Charvi    Female No            \n 9 Anoti     Female Yes           \n10 Dhruv     Male   No            \n# ℹ 31 more rows\n```\n\n\n:::\n:::\n\n\n6 entries are dropped from the dataset.\n\n### Munging the Data\n\nFactoring 'gender' and 'believe_in_god'\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_mod2 <- believe_mod1 %>% \nmutate(gender = as.factor(gender),\n       believe_in_god = as.factor(believe_in_god))\n```\n:::\n\n\n### Counting gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_mod2 %>% \n  dplyr::count(gender) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_0gc3fqz73809iurj8k1t(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_0gc3fqz73809iurj8k1t\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_0gc3fqz73809iurj8k1t(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_0gc3fqz73809iurj8k1t\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 0 }, { i: '2', j: 1 },  ], css_id: 'tinytable_css_3chisy7u4z51bi6n1nfd',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 },  ], css_id: 'tinytable_css_0qsgkd0cqlb2jql78h7v',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_0gc3fqz73809iurj8k1t(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_3chisy7u4z51bi6n1nfd, .table th.tinytable_css_3chisy7u4z51bi6n1nfd { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_0qsgkd0cqlb2jql78h7v, .table th.tinytable_css_0qsgkd0cqlb2jql78h7v { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_0gc3fqz73809iurj8k1t\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">gender</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Female</td>\n                  <td data-row=\"1\" data-col=\"1\">23</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">Male</td>\n                  <td data-row=\"2\" data-col=\"1\">18</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_mod2 %>%\n  gf_bar(~gender, fill = \"gold\") %>%\n  gf_labs(\n    title = \"Gender representation\",\n    x = \"Gender\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Beleive_in_God_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n#### Observation\n\n-   There is a slight imbalance in the gender proportion, but not very significant.\n\n-   Both genders have substantial representation, though not perfectly equal\n\n### Counting believe_in_god\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_mod2 %>% \n  dplyr::count(believe_in_god) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_ko07g1lzbabp7q0fvorr(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_ko07g1lzbabp7q0fvorr\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_ko07g1lzbabp7q0fvorr(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_ko07g1lzbabp7q0fvorr\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 0 }, { i: '2', j: 1 },  ], css_id: 'tinytable_css_3x508w3ne1gh517axojm',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 },  ], css_id: 'tinytable_css_zcl4xbwgjx8672r8a9zf',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_ko07g1lzbabp7q0fvorr(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_3x508w3ne1gh517axojm, .table th.tinytable_css_3x508w3ne1gh517axojm { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_zcl4xbwgjx8672r8a9zf, .table th.tinytable_css_zcl4xbwgjx8672r8a9zf { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_ko07g1lzbabp7q0fvorr\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">believe_in_god</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">No</td>\n                  <td data-row=\"1\" data-col=\"1\">15</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">Yes</td>\n                  <td data-row=\"2\" data-col=\"1\">26</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_mod2 %>% \ngf_bar(~believe_in_god, fill = \"orange\") %>% \ngf_labs(title = \"Do students believe in God?\",\n       x = \"Believes in God\",\n       y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](Beleive_in_God_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n#### Observation\n\n-   Clearly, majority believe in God vs. not believing.\n\n-   Believers outnumber non-believers by nearly 2 to 1\n\n-   The sample has a slight female majority - could this gender imbalance influence the overall belief distribution?\n\n### Belief by Gender\n\n**Counting Belief by Gender**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_mod2 %>% \n    count(across(c(\"gender\", \"believe_in_god\"))) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_nnzyi2eh8yzbfwbse2dq(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_nnzyi2eh8yzbfwbse2dq\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_nnzyi2eh8yzbfwbse2dq(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_nnzyi2eh8yzbfwbse2dq\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 0 }, { i: '4', j: 1 }, { i: '4', j: 2 },  ], css_id: 'tinytable_css_6u673fhe64c8gv2hl48d',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_298m3o7gstbheus3bmv1',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_nnzyi2eh8yzbfwbse2dq(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_6u673fhe64c8gv2hl48d, .table th.tinytable_css_6u673fhe64c8gv2hl48d { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_298m3o7gstbheus3bmv1, .table th.tinytable_css_298m3o7gstbheus3bmv1 { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_nnzyi2eh8yzbfwbse2dq\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">gender</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">believe_in_god</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Female</td>\n                  <td data-row=\"1\" data-col=\"1\">No</td>\n                  <td data-row=\"1\" data-col=\"2\">5</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">Female</td>\n                  <td data-row=\"2\" data-col=\"1\">Yes</td>\n                  <td data-row=\"2\" data-col=\"2\">18</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">Male</td>\n                  <td data-row=\"3\" data-col=\"1\">No</td>\n                  <td data-row=\"3\" data-col=\"2\">10</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">Male</td>\n                  <td data-row=\"4\" data-col=\"1\">Yes</td>\n                  <td data-row=\"4\" data-col=\"2\">8</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n**Visualizing in a Dodged Bar graph**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelieve_mod2 %>%\n  gf_bar(~believe_in_god, fill = ~gender, position = \"dodge\") %>%\n  gf_labs(\n    title = \"Belief in God by Gender\",\n    x = \"Believes in God\",\n    y = \"Count\",\n    fill = \"Gender\"\n  )\n```\n\n::: {.cell-output-display}\n![](Beleive_in_God_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n#### Observation\n\n-   There is a strong belief among females where, **18** are believer and **6** are non-believers\n-   For males, the belief in nearly split where, **8** are believers and **9** arenon-believers\n-   **Gender** seems to be a predictor of religious belief in this student population, with female students nearly twice as likely to believe in God compared to male students.\n\n### Checking the correlation between Gender and Belief with Mosaic Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcd::structable(gender ~ believe_in_god, data = believe_mod2) %>%\n  vcd::mosaic(shade = TRUE, legend = TRUE,\n              main = \"Gender vs Belief in God\",\n              gp = shading_max)\n```\n\n::: {.cell-output-display}\n![](Beleive_in_God_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n#### Observation:\n\n-   Since **p \\< 0.05,** there is statistically significant evidence that gender affects belief in God patterns among students\n\n-   Although it is important to note that, p = 0.044 is barely significant (close to the 0.05 threshold) and the relation might be fairly weak.\n\n-   With a smaller sample, this small of a difference might not be significant\n\n## Conclusion from EDA\n\nThis analysis reveals two key insights about religious belief among art & design students:\n\n**1. Majority maintains traditional belief**\n\n-   Contrary to the hypothesis, **65% of the students believe in God**, a substantial majority that challenges expectations of higher secularism in creative educational environments.\n\n**2. Significant gender divide**\n\n-   A **pronounced gender gap** exists: **18 female students** believe versus **only 8 of males** - a difference that is statistically significant (p = 0.044), though the relationship is relatively weak.\n\n## Inference\n\n**Null hypothesis:** TThe proportion of students who believe in God is 50% - there is no majority preference in either direction.\n\nStatically, **H₀**: p = 0.5\n\n### Performing Binom Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::binom.test(~believe_in_god, data = believe_mod2, success = \"Yes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\ndata:  believe_mod2$believe_in_god  [with success = Yes]\nnumber of successes = 26, number of trials = 41, p-value = 0.1173\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.4693625 0.7787721\nsample estimates:\nprobability of success \n             0.6341463 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::binom.test(~believe_in_god, data = believe_mod2, success = \"Yes\") %>%\n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  estimate statistic p.value parameter conf.low conf.high alternative\n     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl> <chr>      \n1    0.634        26   0.117        41    0.469     0.779 two.sided  \n```\n\n\n:::\n:::\n\n\n### Key Findings\n\n-   The p-value (0.117) indicates we cannot reject the null hypothesis that belief and non-belief are equally distributed (50–50).\n-   Observed Belief rate: **63.4%** of art students believe in God\n-   Not significant at the **0.05** level (p = 0.117).\n-   The true population proportion likely falls between **47% and 78%**\n\nAlthough a numerical majority (63%) identify as believers, the difference is **not statistically significant**, suggesting that this imbalance could occur by chance in a population with equal proportions of belief and non-belief.\n\n## Final interpretation\n\nArt & Design students **do not show a statistically significant tendency** toward belief or non-belief in God. While the 63% belief rate hints at a potential leaning toward theism, the evidence is insufficient to conclude a meaningful departure from an even 50–50 distribution.\n",
    "supporting": [
      "Beleive_in_God_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}