{
  "hash": "229e749db8a88dcc18c06ff44c12b9cf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Are Dads weird?\"\nauthor: \"Ashmita Biswas\"\n---\n\n# Are Dads weird?\n\nPaternal weirdness rating is...weird.\n\n![](images/clipboard-3560242678.png)\n\n## About the Data\n\nThis data set is derived from the peasants of Manipal University where we wanted to understand if SMI dads embarrass their kids more than MIT dads.\n\n## Data Dictionary\n\nQualitative Variables\n\n:   **gender:** Gender of the student where, M = Male, F = Female, NB = Non Binary\n\n:   **college:** Institute within Manipal University, the peasant belongs to.\n\n:   **is_dad_weird:** Is the dad perceived as weird or not, categorized by 'Yes' and 'No'\n\n:   **name:** Name of the student (aka. peasant)\n\n## Hypothesis\n\n-   Do SMI students find their dads to be weirder as compared to MIT?\n\n    **Something interesting to look for:**\n\n-   Is there a bias in gender when it comes do dad weirdness perception of dads?\n\n### Setup\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ purrr     1.1.0\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\nLoading required package: scales\n\n\nAttaching package: 'scales'\n\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n\n\nLoading required package: ggridges\n\n\nNew to ggformula?  Try the tutorials: \n\tlearnr::run_tutorial(\"introduction\", package = \"ggformula\")\n\tlearnr::run_tutorial(\"refining\", package = \"ggformula\")\n\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\n\nAttaching package: 'mosaic'\n\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\n\nThe following object is masked from 'package:scales':\n\n    rescale\n\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n\n\n\nAttaching package: 'skimr'\n\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n\n\n\nAttaching package: 'naniar'\n\n\nThe following object is masked from 'package:skimr':\n\n    n_complete\n\n\n\nAttaching package: 'janitor'\n\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n\n\n\nAttaching package: 'tinytable'\n\n\nThe following object is masked from 'package:ggplot2':\n\n    theme_void\n\n\n\nAttaching package: 'crosstable'\n\n\nThe following object is masked from 'package:purrr':\n\n    compact\n\n\nLoading required package: grid\n\n\nAttaching package: 'vcd'\n\n\nThe following object is masked from 'package:mosaic':\n\n    mplot\n\n\nLoading required package: gnm\n\n\nAttaching package: 'gnm'\n\n\nThe following object is masked from 'package:lattice':\n\n    barley\n\n\n\nAttaching package: 'vcdExtra'\n\n\nThe following object is masked from 'package:dplyr':\n\n    summarise\n```\n\n\n:::\n:::\n\n\n### Inspecting the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweird_dad_data <- read_csv(\"~/Documents/R_work/DataRchive/posts/A3_Ashmita/Datasets/3-weird_dads.csv\") %>%\njanitor::clean_names(case = \"snake\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 65 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): gender, college, is_dad_weird, name\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nweird_dad_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 65 × 4\n   gender college is_dad_weird name   \n   <chr>  <chr>   <chr>        <chr>  \n 1 F      SMI     No           Manya  \n 2 F      SMI     No           Sradha \n 3 M      SMI     No           Arun   \n 4 F      SMI     Yes          Nidhi  \n 5 M      MIT     No           Shaurya\n 6 M      MIT     No           Pratham\n 7 M      MIT     No           Jeevan \n 8 M      SMI     No           Dhruv  \n 9 F      SMI     Yes          Aakrati\n10 M      SMI     Yes          Aakrsh \n# ℹ 55 more rows\n```\n\n\n:::\n:::\n\n\n### Reading the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_data <- read_csv(\"~/Documents/R_work/DataRchive/posts/A3_Ashmita/Datasets/3-weird_dads.csv\") %>%\njanitor::clean_names(case = \"snake\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 65 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): gender, college, is_dad_weird, name\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndad_weird_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 65 × 4\n   gender college is_dad_weird name   \n   <chr>  <chr>   <chr>        <chr>  \n 1 F      SMI     No           Manya  \n 2 F      SMI     No           Sradha \n 3 M      SMI     No           Arun   \n 4 F      SMI     Yes          Nidhi  \n 5 M      MIT     No           Shaurya\n 6 M      MIT     No           Pratham\n 7 M      MIT     No           Jeevan \n 8 M      SMI     No           Dhruv  \n 9 F      SMI     Yes          Aakrati\n10 M      SMI     Yes          Aakrsh \n# ℹ 55 more rows\n```\n\n\n:::\n:::\n\n\n### Checking for missing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_data %>%\n  visdat::vis_miss()\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_data %>%\n  visdat::vis_dat()\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nSeems like some peasants were boggled by the question 'Is your dad weird?' and couldn't comprehend to answer. Hence removing the entries for these confused souls\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod1 <- dad_weird_data %>% \n  naniar::replace_with_na_all(condition = ~ .x %in% common_na_strings) %>% \ndrop_na()\ndad_weird_mod1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 64 × 4\n   gender college is_dad_weird name   \n   <chr>  <chr>   <chr>        <chr>  \n 1 F      SMI     No           Manya  \n 2 F      SMI     No           Sradha \n 3 M      SMI     No           Arun   \n 4 F      SMI     Yes          Nidhi  \n 5 M      MIT     No           Shaurya\n 6 M      MIT     No           Pratham\n 7 M      MIT     No           Jeevan \n 8 M      SMI     No           Dhruv  \n 9 F      SMI     Yes          Aakrati\n10 M      SMI     Yes          Aakrsh \n# ℹ 54 more rows\n```\n\n\n:::\n:::\n\n\nOne entry was dropped from the data set.\n\n### Munging the Data\n\nFactoring 'gender' and 'is_dad_weird'\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 <- dad_weird_mod1 %>% \nmutate(gender = as.factor(gender),\n       is_dad_weird = as.factor(is_dad_weird))\n```\n:::\n\n\n### Examining the Data\n\nTaking a glimpse of the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(dad_weird_mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 64\nColumns: 4\n$ gender       <fct> F, F, M, F, M, M, M, M, F, M, F, M, F, F, M, M, F, M, M, …\n$ college      <chr> \"SMI\", \"SMI\", \"SMI\", \"SMI\", \"MIT\", \"MIT\", \"MIT\", \"SMI\", \"…\n$ is_dad_weird <fct> No, No, No, Yes, No, No, No, No, Yes, Yes, Yes, Yes, No, …\n$ name         <chr> \"Manya\", \"Sradha\", \"Arun\", \"Nidhi\", \"Shaurya\", \"Pratham\",…\n```\n\n\n:::\n:::\n\n\n### Counting gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>% \n  dplyr::count(gender) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_kmp2b2go1rf6zus0b05c(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_kmp2b2go1rf6zus0b05c\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_kmp2b2go1rf6zus0b05c(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_kmp2b2go1rf6zus0b05c\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 0 }, { i: '3', j: 1 },  ], css_id: 'tinytable_css_2hqigdukjzm3myc7xty8',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 },  ], css_id: 'tinytable_css_djiuln9rm5oi5el2g8k8',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_kmp2b2go1rf6zus0b05c(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_2hqigdukjzm3myc7xty8, .table th.tinytable_css_2hqigdukjzm3myc7xty8 { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_djiuln9rm5oi5el2g8k8, .table th.tinytable_css_djiuln9rm5oi5el2g8k8 { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_kmp2b2go1rf6zus0b05c\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">gender</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">F</td>\n                  <td data-row=\"1\" data-col=\"1\">32</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">M</td>\n                  <td data-row=\"2\" data-col=\"1\">31</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">NB</td>\n                  <td data-row=\"3\" data-col=\"1\">1</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>% \n  gf_bar(~gender, fill = \"purple\") %>% \ngf_labs(title = \"Gender distribution\",\n       x = \"Gender\",\n       y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n#### Observation\n\n-   There is nearly equal representation between Female (32) and Male (31) students\n-   Since the representation of Non-binary is one and not significant, for gender related tests, it will be excluded.\n\n### Counting representation for each college\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>% \n  dplyr::count(college) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_w1nu1t7cc54nrh6i9fjy(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_w1nu1t7cc54nrh6i9fjy\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_w1nu1t7cc54nrh6i9fjy(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_w1nu1t7cc54nrh6i9fjy\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 0 }, { i: '2', j: 1 },  ], css_id: 'tinytable_css_8c3geguwosp4ygzowg8j',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 },  ], css_id: 'tinytable_css_pp3qlo58j9cqvev2cfqa',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_w1nu1t7cc54nrh6i9fjy(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_8c3geguwosp4ygzowg8j, .table th.tinytable_css_8c3geguwosp4ygzowg8j { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_pp3qlo58j9cqvev2cfqa, .table th.tinytable_css_pp3qlo58j9cqvev2cfqa { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_w1nu1t7cc54nrh6i9fjy\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">college</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">MIT</td>\n                  <td data-row=\"1\" data-col=\"1\">33</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">SMI</td>\n                  <td data-row=\"2\" data-col=\"1\">31</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>%\n  gf_bar(~college, fill = \"dodgerblue\") %>%\n  gf_labs(\n    title = \"College representation\",\n    x = \"Colleges\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n#### Observation\n\n-   Both colleges are nearly equally represented, hence there is no bias in the data collection\n\n-   The 64-student sample is perfect for college-wise analysis with minimal sampling bias\n\n### Counting is_dad_weird\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>% \n  dplyr::count(is_dad_weird) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_vnjs5uq0lnp5tf8knoro(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_vnjs5uq0lnp5tf8knoro\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_vnjs5uq0lnp5tf8knoro(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_vnjs5uq0lnp5tf8knoro\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 0 }, { i: '2', j: 1 },  ], css_id: 'tinytable_css_8m2624zmtyjwj4d08w0q',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 },  ], css_id: 'tinytable_css_dqe0b2zm8hr7gmmeen49',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_vnjs5uq0lnp5tf8knoro(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_8m2624zmtyjwj4d08w0q, .table th.tinytable_css_8m2624zmtyjwj4d08w0q { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_dqe0b2zm8hr7gmmeen49, .table th.tinytable_css_dqe0b2zm8hr7gmmeen49 { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_vnjs5uq0lnp5tf8knoro\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">is_dad_weird</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">No</td>\n                  <td data-row=\"1\" data-col=\"1\">47</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">Yes</td>\n                  <td data-row=\"2\" data-col=\"1\">17</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>%\n  gf_bar(~is_dad_weird, fill = \"skyblue\") %>%\n  gf_labs(\n    title = \"Do students think their Dads are weird?\",\n    x = \"Is Dad weird?\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n#### Observation\n\n-   Huh! Most students are NOT finding their dad weird, now that's weird.\n\n<!-- -->\n\n-   **Strong 3:1 Ratio**: \"Normal\" dads significantly outnumber \"weird\" dads\n\n### How Dad weirdness relates to Gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>%\n  filter(gender != \"NB\") %>%\n  count(across(c(\"gender\", \"is_dad_weird\"))) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_xjx9wf8qqr275ud4hk3i(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_xjx9wf8qqr275ud4hk3i\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_xjx9wf8qqr275ud4hk3i(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_xjx9wf8qqr275ud4hk3i\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 0 }, { i: '4', j: 1 }, { i: '4', j: 2 },  ], css_id: 'tinytable_css_arqil076n0565zsd4jq2',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_hbqh33tffjbnr2shndzo',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_xjx9wf8qqr275ud4hk3i(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_arqil076n0565zsd4jq2, .table th.tinytable_css_arqil076n0565zsd4jq2 { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_hbqh33tffjbnr2shndzo, .table th.tinytable_css_hbqh33tffjbnr2shndzo { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_xjx9wf8qqr275ud4hk3i\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">gender</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">is_dad_weird</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">F</td>\n                  <td data-row=\"1\" data-col=\"1\">No</td>\n                  <td data-row=\"1\" data-col=\"2\">23</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">F</td>\n                  <td data-row=\"2\" data-col=\"1\">Yes</td>\n                  <td data-row=\"2\" data-col=\"2\">9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">M</td>\n                  <td data-row=\"3\" data-col=\"1\">No</td>\n                  <td data-row=\"3\" data-col=\"2\">24</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">M</td>\n                  <td data-row=\"4\" data-col=\"1\">Yes</td>\n                  <td data-row=\"4\" data-col=\"2\">7</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>%\n   filter(gender != \"NB\") %>%\n  gf_bar(~gender, fill = ~is_dad_weird, position = \"fill\") %>%\n  gf_labs(\n    title = \"Gender vs. Dad Weirdness\",\n    subtitle = \"Do sons and daughters rate dad-cringe differently?\",\n    x = \"Gender\",\n    y = \"Proportion\"\n  )\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n### Observation\n\n-   Nearly identical gender patterns\n\n-   23 Females and 24 Males say that there Dads are not weird\n\n### Dad weirdness for colleges\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>%\n  filter(gender != \"NB\") %>%\n  count(across(c(\"college\", \"is_dad_weird\"))) %>%\n  tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_l2mvlwkgzm1w55pkwzeu(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_l2mvlwkgzm1w55pkwzeu\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_l2mvlwkgzm1w55pkwzeu(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_l2mvlwkgzm1w55pkwzeu\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 0 }, { i: '4', j: 1 }, { i: '4', j: 2 },  ], css_id: 'tinytable_css_20se7b838n50fwbtpfje',}, \n          { positions: [ { i: '0', j: 0 }, { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_km7r4zx74d3rzahp7p1s',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_l2mvlwkgzm1w55pkwzeu(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_20se7b838n50fwbtpfje, .table th.tinytable_css_20se7b838n50fwbtpfje { border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_km7r4zx74d3rzahp7p1s, .table th.tinytable_css_km7r4zx74d3rzahp7p1s { border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_l2mvlwkgzm1w55pkwzeu\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">college</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">is_dad_weird</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">n</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">MIT</td>\n                  <td data-row=\"1\" data-col=\"1\">No</td>\n                  <td data-row=\"1\" data-col=\"2\">28</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">MIT</td>\n                  <td data-row=\"2\" data-col=\"1\">Yes</td>\n                  <td data-row=\"2\" data-col=\"2\">4</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">SMI</td>\n                  <td data-row=\"3\" data-col=\"1\">No</td>\n                  <td data-row=\"3\" data-col=\"2\">19</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">SMI</td>\n                  <td data-row=\"4\" data-col=\"1\">Yes</td>\n                  <td data-row=\"4\" data-col=\"2\">12</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nVisualizing in a Dodge and Proportion Bar graph\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>%\n  gf_bar(~college, fill = ~is_dad_weird, position = \"dodge\") %>%\n  gf_labs(\n    title = \"Dad Weirdness for SMI & MIT\",\n    x = \"College\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n**Let's check their proportions**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndad_weird_mod2 %>%\n  gf_bar(~college, fill = ~is_dad_weird, position = \"fill\") %>%\n  gf_labs(\n    title = \"Dad Weirdness: SMI vs MIT Showdown\",\n    x = \"College\",\n    y = \"Proportion\",\n    fill = \"Weird Dad?\"\n  )\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n#### Observation\n\n-   There seems to be a distinct divide among colleges\n\n-   **MIT Students**: 28 of 32 say dads are NOT weird (too good to be true?)\n\n-   **SMI Students**: 19 of 31 say dads are NOT weird (here's the weirdness!)\n\n-   SMI students are **3x more likely** to report weird dads compared to MIT\n\n### Checking Weridness and College relation statistically by a Mosaic Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcd::structable(college ~ is_dad_weird, data = dad_weird_mod2) %>%\n  vcd::mosaic(shade = TRUE, legend = TRUE,\n              main = \"College vs Dad Weirdness\",\n              gp = shading_max)\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### Observation\n\n-   The **p-value of 0.042** provides **statistically significant evidence** that there is a real difference in dad weirdness perceptions between MIT and SMI students.\n\n-   There appears to be something about the **SMI environment or student demographics** that leads to higher rates of paternal \"weirdness\" perception compared to the MIT campus culture.\n\n## Conclusion from EDA\n\nThis analysis reveals a clear and statistically significant pattern in how students perceive their fathers:\n\n**1. College matters most**\n\n-   **Statistically Significant**: p = 0.042 confirms this is a real pattern, not random chance\n\n-   **Cultural Divide**: Different campus environments appear to shape paternal perception dramatically\n\n**2. Gender doesn't matter**\n\n-   Both male and female students overwhelmingly see dads as normal\n\n**3. Dad approval**\n\n-   73% of students give their fathers a \"normal\" rating\n\n## Inference\n\n**Null Hypothesis:** There is no difference in dad weirdness perceptions between MIT and SMI students - any observed variation occurs by random chance alone.\n\n### Performing Chi-Square Test\n\n**Creating contingency table & running chi-square test**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table <- table(dad_weird_mod2$college, dad_weird_mod2$is_dad_weird)\nxq_test_object <- mosaic::xchisq.test(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  x\nX-squared = 3.4202, df = 1, p-value = 0.0644\n\n   28        5   \n(24.23)  ( 8.77) \n [0.44]   [1.22] \n< 0.76>  <-1.27> \n   \n   19       12   \n(22.77)  ( 8.23) \n [0.47]   [1.30] \n<-0.79>  < 1.31> \n   \nkey:\n\tobserved\n\t(expected)\n\t[contribution to X-squared]\n\t<Pearson residual>\n```\n\n\n:::\n:::\n\n\n-   The p-value of 0.0644 indicates **borderline significance** - while not statistically significant at the conventional 0.05 level, it strongly suggests a meaningful pattern where SMI students consistently report more dad weirdness than expected, while MIT students report less.\n\n**Extracting observed chi-square statistic**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxq_test_object %>%\n  broom::tidy() %>%\n  select(statistic) %>%\n  as.numeric() -> X_squared_observed\nX_squared_observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.420189\n```\n\n\n:::\n:::\n\n\n**Determining the Chi-Square critical value**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX_squared_critical <- qchisq(\n  p = .05,\n  df = (2 - 1) * (2 - 1), \n  lower.tail = FALSE\n)\nX_squared_critical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.841459\n```\n\n\n:::\n:::\n\n\n-   **Bbserved value**: 3.420189\n\n-   **Critical value**: 3.841459\n\n-   **Decision**: Since 3.42 \\< 3.84, your test statistic **does not exceed** the critical threshold\n\n**Visualization for the critical value**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::theme_set(new = ggplot2::theme_minimal())\n\nmosaic::xqchisq(\n  p = 0.95, df = 1,  \n  return = c(\"plot\"), verbose = FALSE,\n  system = \"gg\"\n) %>%\n  gf_labs(\n    title = \"Chi-Square Test: College vs Dad Weirdness\",\n    x = \"Chi-Square Value\", \n    y = \"Density\"\n  ) %>%\n  gf_vline(\n    xintercept = X_squared_observed,\n    color = \"red\", linewidth = 1\n  ) %>%\n  gf_vline(\n    xintercept = X_squared_critical,\n    color = \"dodgerblue\",\n    linewidth = 1\n  ) %>%\n  gf_annotate(\n    x = X_squared_observed - 1, y = 0.25,\n    geom = \"label\", label = \"Observed\\nChi-Square\",\n    fill = \"red\", alpha = 0.3\n  ) %>%\n  gf_annotate(\"curve\", \n    x = X_squared_observed - 1, y = 0.23,\n    xend = X_squared_observed - 0.1, yend = 0.15,\n    linewidth = 0.5, curvature = 0.3,\n    arrow = arrow(length = unit(0.15, \"cm\"))\n  ) %>%\n  gf_annotate(\n    x = X_squared_critical + 1, y = 0.25,\n    geom = \"label\", label = \"Critical\\nChi-Square\",\n    fill = \"lightblue\", alpha = 0.3\n  ) %>%\n  gf_annotate(\"curve\", \n    x = X_squared_critical + 1, y = 0.23,\n    xend = X_squared_critical + 0.1, yend = 0.15,\n    linewidth = 0.5, curvature = -0.3,\n    arrow = arrow(length = unit(0.15, \"cm\"))\n  )\n```\n\n::: {.cell-output-display}\n![](Dads_are_weird_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n-   Observed chi-square value falls in the **\"fail to reject\" region** of the distribution, meaning the difference in dad weirdness perceptions between MIT and SMI, while suggestive, is **not statistically significant** at the conventional 0.05 level.\n\n-   The pattern observed (SMI students reporting more dad weirdness) could reasonably occur by random chance about 6.4% of the time (matching the earlier p-value of 0.0644).\n\n## Final interpretation\n\nDespite the popular “cringey dad” stereotype, most students (73%) see their fathers as completely normal. The most interesting difference appears between institutions: although not quite statistically significant (p = 0.064), the 27-point gap between MIT (88%) and SMI (61%) is hard to ignore. The chi-square result (3.42 vs. 3.84) falls just short of the cutoff, but the consistent pattern and effect size suggest something real may be happening, worth exploring further.\n",
    "supporting": [
      "Dads_are_weird_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}